Repository SOPT-all/35-COLLABORATION-iOS-KORAILTALK, pull requests merged in 2024-11, with the labels that each got.

#7 [Setting] #3 - 스타일 가이드 세팅
  KORAILTALK-iOS/KORAILTALK-iOS.xcodeproj/project.pbxproj
  KORAILTALK-iOS/KORAILTALK-iOS/Global/Extensions/UIString+.swift
  KORAILTALK-iOS/KORAILTALK-iOS/Global/Literals/ColorLiterals.swift
  KORAILTALK-iOS/KORAILTALK-iOS/Global/Literals/FontLiterals.swift
  KORAILTALK-iOS/KORAILTALK-iOS/Global/Resources/Fonts/Pretendard-Medium.otf
  KORAILTALK-iOS/KORAILTALK-iOS/Global/Resources/Fonts/Pretendard-Regular.otf
  KORAILTALK-iOS/KORAILTALK-iOS/Global/Resources/Fonts/Pretendard-SemiBold.otf
  KORAILTALK-iOS/KORAILTALK-iOS/Global/Supporting Files/Info.plist
Labels: 혜린 🪽, Setting ⚙️

#6 [Setting] #4 - NavigationBar Appearance 전역 설정
  KORAILTALK-iOS/KORAILTALK-iOS.xcodeproj/project.pbxproj
  KORAILTALK-iOS/KORAILTALK-iOS/Application/AppDelegate.swift
  KORAILTALK-iOS/KORAILTALK-iOS/Global/Extensions/UIViewController+.swift
  KORAILTALK-iOS/KORAILTALK-iOS/Global/Resources/Assets.xcassets/NavigationBar/Contents.json
  KORAILTALK-iOS/KORAILTALK-iOS/Global/Resources/Assets.xcassets/NavigationBar/icn_arrow_left.imageset/Contents.json
  KORAILTALK-iOS/KORAILTALK-iOS/Global/Resources/Assets.xcassets/NavigationBar/icn_arrow_left.imageset/icn_arrow_left.svg
  KORAILTALK-iOS/KORAILTALK-iOS/Global/Resources/Assets.xcassets/NavigationBar/icn_menu.imageset/Contents.json
  KORAILTALK-iOS/KORAILTALK-iOS/Global/Resources/Assets.xcassets/NavigationBar/icn_menu.imageset/icn_menu.svg
  KORAILTALK-iOS/KORAILTALK-iOS/Global/Resources/Assets.xcassets/NavigationBar/icn_reload.imageset/Contents.json
  KORAILTALK-iOS/KORAILTALK-iOS/Global/Resources/Assets.xcassets/NavigationBar/icn_reload.imageset/icn_reload.svg
  KORAILTALK-iOS/KORAILTALK-iOS/Global/Resources/Assets.xcassets/SeatSelection/Contents.json
  KORAILTALK-iOS/KORAILTALK-iOS/Global/Resources/Assets.xcassets/SeatSelection/icn_arrow_circle.imageset/Contents.json
  KORAILTALK-iOS/KORAILTALK-iOS/Global/Resources/Assets.xcassets/SeatSelection/icn_arrow_circle.imageset/icn_arrow_circle.svg
  KORAILTALK-iOS/KORAILTALK-iOS/Presentation/SeatSelection/SeatSelectionViewController.swift
  KORAILTALK-iOS/KORAILTALK-iOS/Presentation/ViewController.swift
Labels: 호근 😭, Setting ⚙️

#9 [Feat] #5 - 열차 조회 상단 UI 구현
  KORAILTALK-iOS/KORAILTALK-iOS.xcodeproj/project.pbxproj
  KORAILTALK-iOS/KORAILTALK-iOS/Global/Extensions/SelectBottomSheetViewController.swift
  KORAILTALK-iOS/KORAILTALK-iOS/Global/Extensions/UIImage+.swift
  KORAILTALK-iOS/KORAILTALK-iOS/Global/FilterDelegate.swift
  KORAILTALK-iOS/KORAILTALK-iOS/Global/Resources/Assets.xcassets/SelectBottomSheet/Contents.json
  KORAILTALK-iOS/KORAILTALK-iOS/Global/Resources/Assets.xcassets/SelectBottomSheet/icn_check_blue.imageset/Contents.json
  KORAILTALK-iOS/KORAILTALK-iOS/Global/Resources/Assets.xcassets/SelectBottomSheet/icn_check_blue.imageset/icn_check.svg
  KORAILTALK-iOS/KORAILTALK-iOS/Global/Resources/Assets.xcassets/SelectBottomSheet/icn_check_purple.imageset/Contents.json
  KORAILTALK-iOS/KORAILTALK-iOS/Global/Resources/Assets.xcassets/SelectBottomSheet/icn_check_purple.imageset/icn_check-2.svg
  KORAILTALK-iOS/KORAILTALK-iOS/Global/Resources/Assets.xcassets/SelectBottomSheet/icn_x_38.imageset/Contents.json
  KORAILTALK-iOS/KORAILTALK-iOS/Global/Resources/Assets.xcassets/SelectBottomSheet/icn_x_38.imageset/icn_x_38.svg
  KORAILTALK-iOS/KORAILTALK-iOS/Global/Resources/Assets.xcassets/TrainSearch/Contents.json
  KORAILTALK-iOS/KORAILTALK-iOS/Global/Resources/Assets.xcassets/TrainSearch/icn_search_arrow_down.imageset/Contents.json
  KORAILTALK-iOS/KORAILTALK-iOS/Global/Resources/Assets.xcassets/TrainSearch/icn_search_arrow_down.imageset/icn_search_arrow_down.svg
  KORAILTALK-iOS/KORAILTALK-iOS/Global/Resources/Assets.xcassets/TrainSearch/icn_search_arrow_up.imageset/Contents.json
  KORAILTALK-iOS/KORAILTALK-iOS/Global/Resources/Assets.xcassets/TrainSearch/icn_search_arrow_up.imageset/icn_search_arrow_up.svg
  KORAILTALK-iOS/KORAILTALK-iOS/Global/Resources/Assets.xcassets/TrainSearch/icn_trainSearch_arrow_down.imageset/Contents.json
  KORAILTALK-iOS/KORAILTALK-iOS/Global/Resources/Assets.xcassets/TrainSearch/icn_trainSearch_arrow_down.imageset/icn_trainSearch_arrow_down.svg
  KORAILTALK-iOS/KORAILTALK-iOS/Global/SelectBottomSheetTableViewCell.swift
  KORAILTALK-iOS/KORAILTALK-iOS/Presentation/TrainSearch/DateCollectionViewCell.swift
  KORAILTALK-iOS/KORAILTALK-iOS/Presentation/TrainSearch/TrainSearchFilterView.swift
  KORAILTALK-iOS/KORAILTALK-iOS/Presentation/TrainSearch/TrainSearchViewController.swift
Labels: 주리 🐿️, Feat 💻, Style 🖼️

#12 [Feat] #11 - 결제하기 할인 섹션 UI 구현
  KORAILTALK-iOS/KORAILTALK-iOS.xcodeproj/project.pbxproj
  KORAILTALK-iOS/KORAILTALK-iOS/Global/Extensions/UIViewController+.swift
  KORAILTALK-iOS/KORAILTALK-iOS/Global/Resources/Assets.xcassets/NavigationBar/icn_x.imageset/Contents.json
  KORAILTALK-iOS/KORAILTALK-iOS/Global/Resources/Assets.xcassets/NavigationBar/icn_x.imageset/icn_x.svg
  KORAILTALK-iOS/KORAILTALK-iOS/Global/Resources/Assets.xcassets/Payment/Contents.json
  KORAILTALK-iOS/KORAILTALK-iOS/Global/Resources/Assets.xcassets/Payment/btn_payment_adjust.imageset/Contents.json
  KORAILTALK-iOS/KORAILTALK-iOS/Global/Resources/Assets.xcassets/Payment/btn_payment_adjust.imageset/btn_payment_adjust.svg
  KORAILTALK-iOS/KORAILTALK-iOS/Global/Resources/Assets.xcassets/Payment/btn_payment_radio_default.imageset/Contents.json
  KORAILTALK-iOS/KORAILTALK-iOS/Global/Resources/Assets.xcassets/Payment/btn_payment_radio_default.imageset/btn_payment_radio_default.svg
  KORAILTALK-iOS/KORAILTALK-iOS/Global/Resources/Assets.xcassets/Payment/btn_payment_radio_selected.imageset/Contents.json
  KORAILTALK-iOS/KORAILTALK-iOS/Global/Resources/Assets.xcassets/Payment/btn_payment_radio_selected.imageset/btn_payment_radio_selected.svg
  KORAILTALK-iOS/KORAILTALK-iOS/Global/Resources/Assets.xcassets/Payment/icn_payment_arrowdown_default.imageset/Contents.json
  KORAILTALK-iOS/KORAILTALK-iOS/Global/Resources/Assets.xcassets/Payment/icn_payment_arrowdown_default.imageset/icn_payment_arrowdown_default.svg
  KORAILTALK-iOS/KORAILTALK-iOS/Global/Resources/Assets.xcassets/Payment/icn_payment_arrowdown_disabled.imageset/Contents.json
  KORAILTALK-iOS/KORAILTALK-iOS/Global/Resources/Assets.xcassets/Payment/icn_payment_arrowdown_disabled.imageset/icn_payment_arrowdown_disabled.svg
  KORAILTALK-iOS/KORAILTALK-iOS/Presentation/Payment/Component/KorailDiscountCouponButton.swift
  KORAILTALK-iOS/KORAILTALK-iOS/Presentation/Payment/Component/KorailRadioButton.swift
  KORAILTALK-iOS/KORAILTALK-iOS/Presentation/Payment/Component/KorailToolBarButton.swift
  KORAILTALK-iOS/KORAILTALK-iOS/Presentation/Payment/View/PaymentView.swift
  KORAILTALK-iOS/KORAILTALK-iOS/Presentation/Payment/View/SectionView/DiscountSectionDetailView/DiscountCouponView.swift
  KORAILTALK-iOS/KORAILTALK-iOS/Presentation/Payment/View/SectionView/DiscountSectionDetailView/KTXMileageView.swift
  KORAILTALK-iOS/KORAILTALK-iOS/Presentation/Payment/View/SectionView/DiscountSectionDetailView/PointUsageView.swift
  KORAILTALK-iOS/KORAILTALK-iOS/Presentation/Payment/View/SectionView/DiscountSectionView.swift
  KORAILTALK-iOS/KORAILTALK-iOS/Presentation/Payment/View/SectionView/TicketSectionView.swift
  KORAILTALK-iOS/KORAILTALK-iOS/Presentation/Payment/ViewController/PaymentViewController.swift
Labels: 혜린 🪽, Feat 💻, Style 🖼️

#14 [Style] #8 - 좌석선택 기본화면 UI 구현
  KORAILTALK-iOS/KORAILTALK-iOS.xcodeproj/project.pbxproj
  KORAILTALK-iOS/KORAILTALK-iOS/Application/SceneDelegate.swift
  KORAILTALK-iOS/KORAILTALK-iOS/Global/Extensions/NSAttributedString+.swift
  KORAILTALK-iOS/KORAILTALK-iOS/Global/Extensions/Preview/UIView+Preview.swift
  KORAILTALK-iOS/KORAILTALK-iOS/Global/Extensions/UILabel+.swift
  KORAILTALK-iOS/KORAILTALK-iOS/Global/Resources/Assets.xcassets/SeatSelection/Polygon 5.imageset/Contents.json
  KORAILTALK-iOS/KORAILTALK-iOS/Global/Resources/Assets.xcassets/SeatSelection/Polygon 5.imageset/Polygon 5.svg
  KORAILTALK-iOS/KORAILTALK-iOS/Global/Resources/Assets.xcassets/SeatSelection/Rectangle 171.imageset/Contents.json
  KORAILTALK-iOS/KORAILTALK-iOS/Global/Resources/Assets.xcassets/SeatSelection/Rectangle 171.imageset/Rectangle 171.svg
  KORAILTALK-iOS/KORAILTALK-iOS/Global/Resources/Assets.xcassets/SeatSelection/icn_seatMap_outlet.imageset/Contents.json
  KORAILTALK-iOS/KORAILTALK-iOS/Global/Resources/Assets.xcassets/SeatSelection/icn_seatMap_outlet.imageset/icn_seatMap_outlet.svg
  KORAILTALK-iOS/KORAILTALK-iOS/Global/Resources/Assets.xcassets/SeatSelection/icn_seat_backward.imageset/Contents.json
  KORAILTALK-iOS/KORAILTALK-iOS/Global/Resources/Assets.xcassets/SeatSelection/icn_seat_backward.imageset/icn_seat_backward.svg
  KORAILTALK-iOS/KORAILTALK-iOS/Global/Resources/Assets.xcassets/SeatSelection/icn_seat_forward.imageset/Contents.json
  KORAILTALK-iOS/KORAILTALK-iOS/Global/Resources/Assets.xcassets/SeatSelection/icn_seat_forward.imageset/icn_seat_forward.svg
  KORAILTALK-iOS/KORAILTALK-iOS/Global/Resources/Assets.xcassets/SeatSelection/icn_seatmap_backward_activate.imageset/Contents.json
  KORAILTALK-iOS/KORAILTALK-iOS/Global/Resources/Assets.xcassets/SeatSelection/icn_seatmap_backward_activate.imageset/icn_seatmap_backward_activate.svg
  KORAILTALK-iOS/KORAILTALK-iOS/Global/Resources/Assets.xcassets/SeatSelection/icn_seatmap_backward_inactive.imageset/Contents.json
  KORAILTALK-iOS/KORAILTALK-iOS/Global/Resources/Assets.xcassets/SeatSelection/icn_seatmap_backward_inactive.imageset/icn_seatmap_backward_inactive.svg
  KORAILTALK-iOS/KORAILTALK-iOS/Global/Resources/Assets.xcassets/SeatSelection/icn_seatmap_backward_selected.imageset/Contents.json
  KORAILTALK-iOS/KORAILTALK-iOS/Global/Resources/Assets.xcassets/SeatSelection/icn_seatmap_backward_selected.imageset/icn_seatmap_backward_selected.svg
  KORAILTALK-iOS/KORAILTALK-iOS/Global/Resources/Assets.xcassets/SeatSelection/icn_seatmap_forward_activate.imageset/Contents.json
  KORAILTALK-iOS/KORAILTALK-iOS/Global/Resources/Assets.xcassets/SeatSelection/icn_seatmap_forward_activate.imageset/icn_seatmap_forward_activate.svg
  KORAILTALK-iOS/KORAILTALK-iOS/Global/Resources/Assets.xcassets/SeatSelection/icn_seatmap_forward_inactive.imageset/Contents.json
  KORAILTALK-iOS/KORAILTALK-iOS/Global/Resources/Assets.xcassets/SeatSelection/icn_seatmap_forward_inactive.imageset/icn_seatmap_forward_inactive.svg
  KORAILTALK-iOS/KORAILTALK-iOS/Global/Resources/Assets.xcassets/SeatSelection/icn_seatmap_forward_selected.imageset/Contents.json
  KORAILTALK-iOS/KORAILTALK-iOS/Global/Resources/Assets.xcassets/SeatSelection/icn_seatmap_forward_selected.imageset/icn_seatmap_forward_selected.svg
  KORAILTALK-iOS/KORAILTALK-iOS/Network/SeatSelectionMock/SeatsResponse.swift
  KORAILTALK-iOS/KORAILTALK-iOS/Presentation/SeatSelection/DataSource/CoachDataSource.swift
  KORAILTALK-iOS/KORAILTALK-iOS/Presentation/SeatSelection/DataSource/SeatSelectionDataSource.swift
  KORAILTALK-iOS/KORAILTALK-iOS/Presentation/SeatSelection/SeatSelectionViewController.swift
  KORAILTALK-iOS/KORAILTALK-iOS/Presentation/SeatSelection/Views/Cells/CoachCell.swift
  KORAILTALK-iOS/KORAILTALK-iOS/Presentation/SeatSelection/Views/Cells/CoachHeaderCell.swift
  KORAILTALK-iOS/KORAILTALK-iOS/Presentation/SeatSelection/Views/Cells/SeatCell.swift
  KORAILTALK-iOS/KORAILTALK-iOS/Presentation/SeatSelection/Views/Cells/SeatInfoCell.swift
  KORAILTALK-iOS/KORAILTALK-iOS/Presentation/SeatSelection/Views/Cells/WindowCell.swift
  KORAILTALK-iOS/KORAILTALK-iOS/Presentation/SeatSelection/Views/CoachBackgroundView.swift
  KORAILTALK-iOS/KORAILTALK-iOS/Presentation/SeatSelection/Views/Headers/SeatRowHeaderView.swift
  KORAILTALK-iOS/KORAILTALK-iOS/Presentation/SeatSelection/Views/SeatRowView.swift
Labels: 호근 😭, Feat 💻, Style 🖼️

#16 [Feat] #13 - 결제하기 뷰 모달 기능 구현
  KORAILTALK-iOS/KORAILTALK-iOS.xcodeproj/project.pbxproj
  KORAILTALK-iOS/KORAILTALK-iOS/Global/Resources/Assets.xcassets/Payment/Property 1=btn_payment_checkbox_square_default.imageset/Contents.json
  KORAILTALK-iOS/KORAILTALK-iOS/Global/Resources/Assets.xcassets/Payment/Property 1=btn_payment_checkbox_square_default.imageset/Property 1=btn_payment_checkbox_square_default.svg
  KORAILTALK-iOS/KORAILTALK-iOS/Global/Resources/Assets.xcassets/Payment/Property 1=btn_payment_checkbox_square_selected.imageset/Contents.json
  KORAILTALK-iOS/KORAILTALK-iOS/Global/Resources/Assets.xcassets/Payment/Property 1=btn_payment_checkbox_square_selected.imageset/Property 1=btn_payment_checkbox_square_selected.svg
  KORAILTALK-iOS/KORAILTALK-iOS/Global/Resources/Assets.xcassets/Payment/btn_coupon_patriotdiscount_patriotnumber.imageset/Contents.json
  KORAILTALK-iOS/KORAILTALK-iOS/Global/Resources/Assets.xcassets/Payment/btn_coupon_patriotdiscount_patriotnumber.imageset/btn_coupon_patriotdiscount_patriotnumber.svg
  KORAILTALK-iOS/KORAILTALK-iOS/Global/Resources/Assets.xcassets/Payment/btn_point_lpoint_check.imageset/Contents.json
  KORAILTALK-iOS/KORAILTALK-iOS/Global/Resources/Assets.xcassets/Payment/btn_point_lpoint_check.imageset/btn_point_lpoint_check.svg
  KORAILTALK-iOS/KORAILTALK-iOS/Presentation/Payment/Component/KorailDropDownButton.swift
  KORAILTALK-iOS/KORAILTALK-iOS/Presentation/Payment/View/SectionView/DiscountSectionDetailView/DiscountCouponView.swift
  KORAILTALK-iOS/KORAILTALK-iOS/Presentation/Payment/View/SectionView/DiscountSectionDetailView/KTXMileageView.swift
  KORAILTALK-iOS/KORAILTALK-iOS/Presentation/Payment/View/SectionView/DiscountSectionDetailView/PointUsageView.swift
  KORAILTALK-iOS/KORAILTALK-iOS/Presentation/Payment/View/SectionView/DiscountSectionView.swift
  KORAILTALK-iOS/KORAILTALK-iOS/Presentation/Payment/View/SectionView/ModalView/LPointModalView.swift
  KORAILTALK-iOS/KORAILTALK-iOS/Presentation/Payment/View/SectionView/ModalView/ModalBaseView.swift
  KORAILTALK-iOS/KORAILTALK-iOS/Presentation/Payment/View/SectionView/ModalView/VeteranDiscountView.swift
  KORAILTALK-iOS/KORAILTALK-iOS/Presentation/Payment/ViewController/ModalViewController/LPointModalViewController.swift
  KORAILTALK-iOS/KORAILTALK-iOS/Presentation/Payment/ViewController/ModalViewController/VeteranDiscountViewController.swift
  KORAILTALK-iOS/KORAILTALK-iOS/Presentation/Payment/ViewController/PaymentViewController.swift
Labels: 혜린 🪽, Feat 💻, Style 🖼️

#18 [Feat] 열차 조회 테이블 UI
  KORAILTALK-iOS/KORAILTALK-iOS.xcodeproj/project.pbxproj
  KORAILTALK-iOS/KORAILTALK-iOS/Global/Extensions/SelectBottomSheetViewController.swift
  KORAILTALK-iOS/KORAILTALK-iOS/Global/FilterDelegate.swift
  KORAILTALK-iOS/KORAILTALK-iOS/Global/Resources/Assets.xcassets/TrainDetailBottomSheet/Contents.json
  KORAILTALK-iOS/KORAILTALK-iOS/Global/Resources/Assets.xcassets/TrainDetailBottomSheet/icn_trainSearch_arrow_right_blue.imageset/Contents.json
  KORAILTALK-iOS/KORAILTALK-iOS/Global/Resources/Assets.xcassets/TrainDetailBottomSheet/icn_trainSearch_arrow_right_blue.imageset/icn_trainSearch_arrow_right-2.svg
  KORAILTALK-iOS/KORAILTALK-iOS/Global/Resources/Assets.xcassets/TrainDetailBottomSheet/icn_trainSearch_money.imageset/Contents.json
  KORAILTALK-iOS/KORAILTALK-iOS/Global/Resources/Assets.xcassets/TrainDetailBottomSheet/icn_trainSearch_money.imageset/icn_trainSearch_money.svg
  KORAILTALK-iOS/KORAILTALK-iOS/Global/Resources/Assets.xcassets/TrainDetailBottomSheet/icn_trainSearch_timetable.imageset/Contents.json
  KORAILTALK-iOS/KORAILTALK-iOS/Global/Resources/Assets.xcassets/TrainDetailBottomSheet/icn_trainSearch_timetable.imageset/icn_trainSearch_timetable.svg
  KORAILTALK-iOS/KORAILTALK-iOS/Global/Resources/Assets.xcassets/TrainDetailBottomSheet/img_traininfo_fee.imageset/Contents.json
  KORAILTALK-iOS/KORAILTALK-iOS/Global/Resources/Assets.xcassets/TrainDetailBottomSheet/img_traininfo_fee.imageset/img_traininfo_fee.jpg
  KORAILTALK-iOS/KORAILTALK-iOS/Global/Resources/Assets.xcassets/TrainDetailBottomSheet/img_traininfo_fee.imageset/img_traininfo_fee@2x.jpg
  KORAILTALK-iOS/KORAILTALK-iOS/Global/Resources/Assets.xcassets/TrainDetailBottomSheet/img_traininfo_fee.imageset/img_traininfo_fee@3x.jpg
  KORAILTALK-iOS/KORAILTALK-iOS/Global/Resources/Assets.xcassets/TrainDetailBottomSheet/img_traininfo_timetable.imageset/Contents.json
  KORAILTALK-iOS/KORAILTALK-iOS/Global/Resources/Assets.xcassets/TrainDetailBottomSheet/img_traininfo_timetable.imageset/img_traininfo_timetable.jpg
  KORAILTALK-iOS/KORAILTALK-iOS/Global/Resources/Assets.xcassets/TrainDetailBottomSheet/img_traininfo_timetable.imageset/img_traininfo_timetable@2x.jpg
  KORAILTALK-iOS/KORAILTALK-iOS/Global/Resources/Assets.xcassets/TrainDetailBottomSheet/img_traininfo_timetable.imageset/img_traininfo_timetable@3x.jpg
  KORAILTALK-iOS/KORAILTALK-iOS/Global/Resources/Assets.xcassets/TrainSearch/icn_trainSearch_arrow_right.imageset/Contents.json
  KORAILTALK-iOS/KORAILTALK-iOS/Global/Resources/Assets.xcassets/TrainSearch/icn_trainSearch_arrow_right.imageset/icn_trainSearch_arrow_right.svg
  KORAILTALK-iOS/KORAILTALK-iOS/Presentation/TrainSearch/TrainDetailBottomSheetViewController.swift
  KORAILTALK-iOS/KORAILTALK-iOS/Presentation/TrainSearch/TrainInfoTableViewCell.swift
  KORAILTALK-iOS/KORAILTALK-iOS/Presentation/TrainSearch/TrainPriceButton.swift
  KORAILTALK-iOS/KORAILTALK-iOS/Presentation/TrainSearch/TrainSearchFilterView.swift
  KORAILTALK-iOS/KORAILTALK-iOS/Presentation/TrainSearch/TrainSearchViewController.swift
Labels: 주리 🐿️, Feat 💻, Style 🖼️

#20 [Feat] #15 - 좌석선택 BottomView와 팝업 구현
  KORAILTALK-iOS/KORAILTALK-iOS.xcodeproj/project.pbxproj
  KORAILTALK-iOS/KORAILTALK-iOS/Global/Extensions/CALayer+.swift
  KORAILTALK-iOS/KORAILTALK-iOS/Global/Resources/Assets.xcassets/SeatSelection/Rectangle 174.imageset/Contents.json
  KORAILTALK-iOS/KORAILTALK-iOS/Global/Resources/Assets.xcassets/SeatSelection/Rectangle 174.imageset/Rectangle 174.png
  KORAILTALK-iOS/KORAILTALK-iOS/Global/Resources/Assets.xcassets/SeatSelection/Rectangle 174.imageset/Rectangle 174@2x.png
  KORAILTALK-iOS/KORAILTALK-iOS/Global/Resources/Assets.xcassets/SeatSelection/Rectangle 174.imageset/Rectangle 174@3x.png
  KORAILTALK-iOS/KORAILTALK-iOS/Presentation/SeatSelection/DataSource/CoachDataSource.swift
  KORAILTALK-iOS/KORAILTALK-iOS/Presentation/SeatSelection/DataSource/SeatSelectionDataSource.swift
  KORAILTALK-iOS/KORAILTALK-iOS/Presentation/SeatSelection/ViewController/SeatSelectionViewController.swift
  KORAILTALK-iOS/KORAILTALK-iOS/Presentation/SeatSelection/Views/BottomSelectionView.swift
  KORAILTALK-iOS/KORAILTALK-iOS/Presentation/SeatSelection/Views/Cells/SeatCell.swift
  KORAILTALK-iOS/KORAILTALK-iOS/Presentation/SeatSelection/Views/Headers/SeatRowHeaderView.swift
  KORAILTALK-iOS/KORAILTALK-iOS/Presentation/SeatSelection/Views/Popup/BasePopupViewController.swift
  KORAILTALK-iOS/KORAILTALK-iOS/Presentation/SeatSelection/Views/Popup/OutletPopupViewController.swift
  KORAILTALK-iOS/KORAILTALK-iOS/Presentation/SeatSelection/Views/Popups/BasePopupView.swift
  KORAILTALK-iOS/KORAILTALK-iOS/Presentation/SeatSelection/Views/SeatRowView.swift
Labels: 호근 😭, Feat 💻, Style 🖼️

#27 [Setting] #26 - 네트워크 초기 세팅 및 L.Point APi 임시 연결
  .gitignore
  KORAILTALK-iOS/KORAILTALK-iOS.xcodeproj/project.pbxproj
  KORAILTALK-iOS/KORAILTALK-iOS/Application/SceneDelegate.swift
  KORAILTALK-iOS/KORAILTALK-iOS/Global/Supporting Files/Info.plist
  KORAILTALK-iOS/KORAILTALK-iOS/Network/Base/BaseService.swift
  KORAILTALK-iOS/KORAILTALK-iOS/Network/Base/BaseTargetType.swift
  KORAILTALK-iOS/KORAILTALK-iOS/Network/Base/MoyaPlugin.swift
  KORAILTALK-iOS/KORAILTALK-iOS/Network/Base/NetworkResult.swift
  KORAILTALK-iOS/KORAILTALK-iOS/Network/Base/NetworkService.swift
  KORAILTALK-iOS/KORAILTALK-iOS/Network/User/DTO/LPointResponseDTO.swift
  KORAILTALK-iOS/KORAILTALK-iOS/Network/User/UserAPI.swift
  KORAILTALK-iOS/KORAILTALK-iOS/Network/User/UserService.swift
  KORAILTALK-iOS/KORAILTALK-iOS/Presentation/Payment/ViewController/ModalViewController/LPointModalViewController.swift
Labels: 혜린 🪽, Network 📡, Setting ⚙️

#24 [Fix] #23 테이블 뷰의 버튼이 작동하지 않았던 이슈 해결
  KORAILTALK-iOS/KORAILTALK-iOS/Presentation/TrainSearch/TrainInfoTableViewCell.swift
Labels: 주리 🐿️, Fix 🔨

#22 [Feat] #19 MyTicket UI
  KORAILTALK-iOS/KORAILTALK-iOS.xcodeproj/project.pbxproj
  KORAILTALK-iOS/KORAILTALK-iOS/Global/Components/SelectBottomSheetController.swift
  KORAILTALK-iOS/KORAILTALK-iOS/Global/Components/SelectBottomSheetTableViewCell.swift
  KORAILTALK-iOS/KORAILTALK-iOS/Global/Components/TrainPriceButton.swift
  KORAILTALK-iOS/KORAILTALK-iOS/Global/Extensions/UIView+.swift
  KORAILTALK-iOS/KORAILTALK-iOS/Global/Resources/Assets.xcassets/MyTicket/Contents.json
  KORAILTALK-iOS/KORAILTALK-iOS/Global/Resources/Assets.xcassets/MyTicket/btn_ticket_share.imageset/Contents.json
  KORAILTALK-iOS/KORAILTALK-iOS/Global/Resources/Assets.xcassets/MyTicket/btn_ticket_share.imageset/btn_ticket_share.svg
  KORAILTALK-iOS/KORAILTALK-iOS/Global/Resources/Assets.xcassets/MyTicket/cmp_myTicket_btm navbar.imageset/Contents.json
  KORAILTALK-iOS/KORAILTALK-iOS/Global/Resources/Assets.xcassets/MyTicket/cmp_myTicket_btm navbar.imageset/cmp_myTicket_btm navbar.jpg
  KORAILTALK-iOS/KORAILTALK-iOS/Global/Resources/Assets.xcassets/MyTicket/cmp_myTicket_btm navbar.imageset/cmp_myTicket_btm navbar@2x.jpg
  KORAILTALK-iOS/KORAILTALK-iOS/Global/Resources/Assets.xcassets/MyTicket/cmp_myTicket_btm navbar.imageset/cmp_myTicket_btm navbar@3x.jpg
  KORAILTALK-iOS/KORAILTALK-iOS/Global/Resources/Assets.xcassets/MyTicket/cmp_myTicket_tab bar.imageset/Contents.json
  KORAILTALK-iOS/KORAILTALK-iOS/Global/Resources/Assets.xcassets/MyTicket/cmp_myTicket_tab bar.imageset/cmp_myTicket_tab bar.jpg
  KORAILTALK-iOS/KORAILTALK-iOS/Global/Resources/Assets.xcassets/MyTicket/cmp_myTicket_tab bar.imageset/cmp_myTicket_tab bar@2x.jpg
  KORAILTALK-iOS/KORAILTALK-iOS/Global/Resources/Assets.xcassets/MyTicket/cmp_myTicket_tab bar.imageset/cmp_myTicket_tab bar@3x.jpg
  KORAILTALK-iOS/KORAILTALK-iOS/Global/Resources/Assets.xcassets/MyTicket/icn_myticket_help.imageset/Contents.json
  KORAILTALK-iOS/KORAILTALK-iOS/Global/Resources/Assets.xcassets/MyTicket/icn_myticket_help.imageset/icn_myticket_help.svg
  KORAILTALK-iOS/KORAILTALK-iOS/Global/Resources/Assets.xcassets/MyTicket/icn_myticket_refresh_L.imageset/Contents.json
  KORAILTALK-iOS/KORAILTALK-iOS/Global/Resources/Assets.xcassets/MyTicket/icn_myticket_refresh_L.imageset/icn_myticket_refresh_L.svg
  KORAILTALK-iOS/KORAILTALK-iOS/Global/Resources/Assets.xcassets/MyTicket/icn_myticket_report.imageset/Contents.json
  KORAILTALK-iOS/KORAILTALK-iOS/Global/Resources/Assets.xcassets/MyTicket/icn_myticket_report.imageset/icn_myticket_report.svg
  KORAILTALK-iOS/KORAILTALK-iOS/Global/Resources/Assets.xcassets/MyTicket/icn_myticket_sms.imageset/Contents.json
  KORAILTALK-iOS/KORAILTALK-iOS/Global/Resources/Assets.xcassets/MyTicket/icn_myticket_sms.imageset/icn_myticket_sms.svg
  KORAILTALK-iOS/KORAILTALK-iOS/Global/Resources/Assets.xcassets/MyTicket/img_myticket_bg.imageset/Contents.json
  KORAILTALK-iOS/KORAILTALK-iOS/Global/Resources/Assets.xcassets/MyTicket/img_myticket_bg.imageset/img_myticket_bg.svg
  KORAILTALK-iOS/KORAILTALK-iOS/Global/Resources/Assets.xcassets/MyTicket/img_myticket_qr.imageset/Contents.json
  KORAILTALK-iOS/KORAILTALK-iOS/Global/Resources/Assets.xcassets/MyTicket/img_myticket_qr.imageset/img_myticket_qr.jpg
  KORAILTALK-iOS/KORAILTALK-iOS/Global/Resources/Assets.xcassets/MyTicket/img_myticket_qr.imageset/img_myticket_qr@2x.jpg
  KORAILTALK-iOS/KORAILTALK-iOS/Global/Resources/Assets.xcassets/MyTicket/img_myticket_qr.imageset/img_myticket_qr@3x.jpg
  KORAILTALK-iOS/KORAILTALK-iOS/Global/Resources/ios_korail.json
  KORAILTALK-iOS/KORAILTALK-iOS/Presentation/MyTicket/Component/MyTicketBlueButton.swift
  KORAILTALK-iOS/KORAILTALK-iOS/Presentation/MyTicket/Component/MyTicketRoundedStrokeButton.swift
  KORAILTALK-iOS/KORAILTALK-iOS/Presentation/MyTicket/View/MyTicketView.swift
  KORAILTALK-iOS/KORAILTALK-iOS/Presentation/MyTicket/ViewController/MyTicketViewController.swift
  KORAILTALK-iOS/KORAILTALK-iOS/Presentation/TrainSearch/Component/DateCollectionViewCell.swift
  KORAILTALK-iOS/KORAILTALK-iOS/Presentation/TrainSearch/Component/TrainInfoTableViewCell.swift
  KORAILTALK-iOS/KORAILTALK-iOS/Presentation/TrainSearch/View/TrainDetailBottomSheetViewController.swift
  KORAILTALK-iOS/KORAILTALK-iOS/Presentation/TrainSearch/View/TrainSearchFilterView.swift
  KORAILTALK-iOS/KORAILTALK-iOS/Presentation/TrainSearch/View/TrainSearchViewController.swift
Labels: 주리 🐿️, Feat 💻, Style 🖼️

#25 [Feat] #21 - 승차권 정보 확인 UI
  KORAILTALK-iOS/KORAILTALK-iOS.xcodeproj/project.pbxproj
  KORAILTALK-iOS/KORAILTALK-iOS/Global/Extensions/NSAttributedString+.swift
  KORAILTALK-iOS/KORAILTALK-iOS/Global/Extensions/UILabel+.swift
  KORAILTALK-iOS/KORAILTALK-iOS/Global/Resources/Assets.xcassets/SeatSelection/icn_money.imageset/Contents.json
  KORAILTALK-iOS/KORAILTALK-iOS/Global/Resources/Assets.xcassets/SeatSelection/icn_money.imageset/icn_money.svg
  KORAILTALK-iOS/KORAILTALK-iOS/Global/Resources/Assets.xcassets/SeatSelection/icn_traincheck_passenger.imageset/Contents.json
  KORAILTALK-iOS/KORAILTALK-iOS/Global/Resources/Assets.xcassets/SeatSelection/icn_traincheck_passenger.imageset/icn_traincheck_passenger.svg
  KORAILTALK-iOS/KORAILTALK-iOS/Global/Resources/Assets.xcassets/SeatSelection/icn_traincheck_seat.imageset/Contents.json
  KORAILTALK-iOS/KORAILTALK-iOS/Global/Resources/Assets.xcassets/SeatSelection/icn_traincheck_seat.imageset/icn_traincheck_seat.svg
  KORAILTALK-iOS/KORAILTALK-iOS/Presentation/SeatSelection/ViewController/TrainCheckViewController.swift
  KORAILTALK-iOS/KORAILTALK-iOS/Presentation/SeatSelection/Views/Cells/WindowCell.swift
  KORAILTALK-iOS/KORAILTALK-iOS/Presentation/SeatSelection/Views/PaymentActionsView.swift
  KORAILTALK-iOS/KORAILTALK-iOS/Presentation/SeatSelection/Views/Popup/TrainCheckPopupViewController.swift
  KORAILTALK-iOS/KORAILTALK-iOS/Presentation/SeatSelection/Views/TrainCheckView.swift
Labels: 호근 😭, Feat 💻, Style 🖼️

#32 [Feat] #17 - 결제하기 뷰 결제 수단 섹션 UI 구현
  KORAILTALK-iOS/KORAILTALK-iOS.xcodeproj/project.pbxproj
  KORAILTALK-iOS/KORAILTALK-iOS/Global/Components/SelectBottomSheetController.swift
  KORAILTALK-iOS/KORAILTALK-iOS/Global/Resources/Assets.xcassets/Payment/btn_payment_cardscan.imageset/Contents.json
  KORAILTALK-iOS/KORAILTALK-iOS/Global/Resources/Assets.xcassets/Payment/btn_payment_cardscan.imageset/btn_payment_cardscan.svg
  KORAILTALK-iOS/KORAILTALK-iOS/Global/Resources/Assets.xcassets/Payment/img_korailXtoss_logo.imageset/Contents.json
  KORAILTALK-iOS/KORAILTALK-iOS/Global/Resources/Assets.xcassets/Payment/img_korailXtoss_logo.imageset/img_korailXtoss_logo.png
  KORAILTALK-iOS/KORAILTALK-iOS/Global/Resources/Assets.xcassets/Payment/img_korailXtoss_logo.imageset/img_korailXtoss_logo@2x.png
  KORAILTALK-iOS/KORAILTALK-iOS/Global/Resources/Assets.xcassets/Payment/img_korailXtoss_logo.imageset/img_korailXtoss_logo@3x.png
  KORAILTALK-iOS/KORAILTALK-iOS/Global/Resources/Assets.xcassets/Payment/img_korailXtoss_logo_selected.imageset/Contents.json
  KORAILTALK-iOS/KORAILTALK-iOS/Global/Resources/Assets.xcassets/Payment/img_korailXtoss_logo_selected.imageset/img_korailXtoss_logo_selected.png
  KORAILTALK-iOS/KORAILTALK-iOS/Global/Resources/Assets.xcassets/Payment/img_korailXtoss_logo_selected.imageset/img_korailXtoss_logo_selected@2x.png
  KORAILTALK-iOS/KORAILTALK-iOS/Global/Resources/Assets.xcassets/Payment/img_korailXtoss_logo_selected.imageset/img_korailXtoss_logo_selected@3x.png
  KORAILTALK-iOS/KORAILTALK-iOS/Global/Resources/Assets.xcassets/Payment/img_payment_easypayment_event.imageset/Contents.json
  KORAILTALK-iOS/KORAILTALK-iOS/Global/Resources/Assets.xcassets/Payment/img_payment_easypayment_event.imageset/img_payment_easypayment_event.svg
  KORAILTALK-iOS/KORAILTALK-iOS/Presentation/Payment/Component/KorailDropDownButton.swift
  KORAILTALK-iOS/KORAILTALK-iOS/Presentation/Payment/Model/SimplePayModel.swift
  KORAILTALK-iOS/KORAILTALK-iOS/Presentation/Payment/View/PaymentView.swift
  KORAILTALK-iOS/KORAILTALK-iOS/Presentation/Payment/View/SectionView/DiscountSectionDetailView/DiscountCouponView.swift
  KORAILTALK-iOS/KORAILTALK-iOS/Presentation/Payment/View/SectionView/ModalView/MostUsedCardBottomSheetViewController.swift
  KORAILTALK-iOS/KORAILTALK-iOS/Presentation/Payment/View/SectionView/ModalView/VeteranDiscountView.swift
  KORAILTALK-iOS/KORAILTALK-iOS/Presentation/Payment/View/SectionView/PaymentMethodSectionDetailView/CardPayView.swift
  KORAILTALK-iOS/KORAILTALK-iOS/Presentation/Payment/View/SectionView/PaymentMethodSectionDetailView/SimplePayCollectionViewCell.swift
  KORAILTALK-iOS/KORAILTALK-iOS/Presentation/Payment/View/SectionView/PaymentMethodSectionDetailView/SimplePayView.swift
  KORAILTALK-iOS/KORAILTALK-iOS/Presentation/Payment/View/SectionView/PaymentMethodSectionView.swift
  KORAILTALK-iOS/KORAILTALK-iOS/Presentation/Payment/ViewController/PaymentViewController.swift
Labels: 혜린 🪽, Feat 💻, Style 🖼️

#34 [Feat] 열차 조회 API 연결
  KORAILTALK-iOS/KORAILTALK-iOS.xcodeproj/project.pbxproj
  KORAILTALK-iOS/KORAILTALK-iOS/Global/Resources/Assets.xcassets/TrainSearch/icn_trainSearch_dash.imageset/Contents.json
  KORAILTALK-iOS/KORAILTALK-iOS/Global/Resources/Assets.xcassets/TrainSearch/icn_trainSearch_dash.imageset/icn_trainSearch_dash.svg
  KORAILTALK-iOS/KORAILTALK-iOS/Network/Base/NetworkService.swift
  KORAILTALK-iOS/KORAILTALK-iOS/Network/Timetables/TimetableAPI.swift
  KORAILTALK-iOS/KORAILTALK-iOS/Network/Timetables/TimetableResponseDTO.swift
  KORAILTALK-iOS/KORAILTALK-iOS/Network/Timetables/TimetableService.swift
  KORAILTALK-iOS/KORAILTALK-iOS/Presentation/MyTicket/Component/MyTicketRoundedStrokeButton.swift
  KORAILTALK-iOS/KORAILTALK-iOS/Presentation/TrainSearch/Component/TrainInfoTableViewCell.swift
  KORAILTALK-iOS/KORAILTALK-iOS/Presentation/TrainSearch/View/TrainDetailBottomSheetViewController.swift
  KORAILTALK-iOS/KORAILTALK-iOS/Presentation/TrainSearch/View/TrainSearchFilterView.swift
  KORAILTALK-iOS/KORAILTALK-iOS/Presentation/TrainSearch/View/TrainSearchViewController.swift
Labels: 주리 🐿️, Feat 💻, Network 📡

#36 [Feat] #33 - 결제하기 뷰 결제 상세 및 하단 버튼 구현
  KORAILTALK-iOS/KORAILTALK-iOS.xcodeproj/project.pbxproj
  KORAILTALK-iOS/KORAILTALK-iOS/Global/Extensions/String+.swift
  KORAILTALK-iOS/KORAILTALK-iOS/Global/Extensions/UIView+.swift
  KORAILTALK-iOS/KORAILTALK-iOS/Presentation/Payment/View/PaymentView.swift
  KORAILTALK-iOS/KORAILTALK-iOS/Presentation/Payment/View/SectionView/ModalView/LPointModalView.swift
  KORAILTALK-iOS/KORAILTALK-iOS/Presentation/Payment/View/SectionView/PaymentDetailSectionView.swift
  KORAILTALK-iOS/KORAILTALK-iOS/Presentation/Payment/ViewController/ModalViewController/LPointModalViewController.swift
  KORAILTALK-iOS/KORAILTALK-iOS/Presentation/Payment/ViewController/PaymentViewController.swift
Labels: 혜린 🪽, Feat 💻, Style 🖼️

#37 [Feat] 티켓 조회 API
  KORAILTALK-iOS/KORAILTALK-iOS.xcodeproj/project.pbxproj
  KORAILTALK-iOS/KORAILTALK-iOS/Network/Base/NetworkService.swift
  KORAILTALK-iOS/KORAILTALK-iOS/Network/Tickets/TicketsAPI.swift
  KORAILTALK-iOS/KORAILTALK-iOS/Network/Tickets/TicketsResponseDTO.swift
  KORAILTALK-iOS/KORAILTALK-iOS/Network/Tickets/TicketsService.swift
  KORAILTALK-iOS/KORAILTALK-iOS/Presentation/MyTicket/View/MyTicketView.swift
  KORAILTALK-iOS/KORAILTALK-iOS/Presentation/MyTicket/ViewController/MyTicketViewController.swift
Labels: 주리 🐿️, Feat 💻, Network 📡

#40 [Feat] #39 - L.Point 조회 API 연결
  KORAILTALK-iOS/KORAILTALK-iOS/Presentation/Payment/View/SectionView/ModalView/LPointModalView.swift
  KORAILTALK-iOS/KORAILTALK-iOS/Presentation/Payment/ViewController/ModalViewController/LPointModalViewController.swift
Labels: 혜린 🪽, Feat 💻, Network 📡

#45 [Feat] #41 - 발권하기 API 연결
  KORAILTALK-iOS/KORAILTALK-iOS.xcodeproj/project.pbxproj
  KORAILTALK-iOS/KORAILTALK-iOS/Network/Base/BaseService.swift
  KORAILTALK-iOS/KORAILTALK-iOS/Network/Tickets/TicketsAPI.swift
  KORAILTALK-iOS/KORAILTALK-iOS/Network/Tickets/TicketsRequestDTO.swift
  KORAILTALK-iOS/KORAILTALK-iOS/Network/Tickets/TicketsService.swift
  KORAILTALK-iOS/KORAILTALK-iOS/Presentation/Payment/View/PaymentView.swift
  KORAILTALK-iOS/KORAILTALK-iOS/Presentation/Payment/View/SectionView/PaymentDetailSectionView.swift
  KORAILTALK-iOS/KORAILTALK-iOS/Presentation/Payment/View/SectionView/TicketSectionView.swift
  KORAILTALK-iOS/KORAILTALK-iOS/Presentation/Payment/ViewController/PaymentViewController.swift
Labels: 혜린 🪽, Feat 💻, Network 📡
